### ISSUE TITLE
Sentence-level BLEU for short sentences

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#25]
See http://quest.ms.mff.cuni.cz:7280/tasks/212-211/compare

system          |  translation             | BLEU
------------------|-------------------------|---------
Reference     |  Jsem optimista .   | 
commercial1 | Já jsem optimista . |  0.5946 
CU-Chimera |  Jsem optimista .    | **0**

So *CU-Chimera* produced a perfect (same-as-reference) translation, but it got sentence-level BLEU=0,
while *commercial1* produced a different translation and it got non-zero BLEU.

What should be the BLEU of a three-word translation identical to the reference?
According to mteval-v13a.pl, it should be 1, because even for n=4, the precision is 1.
Why? [If the number of test 4-grams is 0, `$iscore = 0`](https://github.com/ufal/qtleap/blob/master/cuni_train/bin/mteval-v13a.pl#L855-L858),
but [`$iscore` is used as an exponent](https://github.com/ufal/qtleap/blob/master/cuni_train/bin/mteval-v13a.pl#L868), so the 4-gram precision is exp(0).

So I suggest to change [this code](https://github.com/choko/MT-ComparEval/blob/master/libs/Metrics/Precision.php#L51-L52) to `$precision = 1`
and similarly, in [the implementation of recall](https://github.com/choko/MT-ComparEval/blob/master/libs/Metrics/Recall.php#L52) there should be `$recall = 1`.

**Comment by choko** [comment]
Done in a39f9c3d815630008657b09b88219a2b78354760.

**Comment by martinpopel** [comment]
http://quest.ms.mff.cuni.cz:7280/tasks/212-211/compare still shows the BLEU=0 for "Jsem optimista ."

**Comment by choko** [comment]
I'm sorry, I need to reimport tasks.

**Comment by choko** [comment]
I guess it is fixed now: http://quest.ms.mff.cuni.cz:7280/tasks/212-211/compare

**Comment by martinpopel** [comment]
Yes, it's fixed (just the URL of commercial1 CU-Chimera is now http://quest.ms.mff.cuni.cz:7280/tasks/214-215/compare ).
